### ISSUE TITLE
[bug] "CoreDNS - Forward request duration" broken?

### ISSUE THREAD

**Issue by uhthomas** [dotdc/grafana-dashboards-kubernetes#104]
### Describe the bug

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/35aa6566-3cb3-4235-bc5f-84c78aa528b6)

**Comment by dotdc** [comment]
Hi @uhthomas,

After a quick look, I don't have the `coredns_forward_request_duration_seconds_bucket` metric on my side, that's why I have `no data`, but I don't have the error. 

Do you have the `coredns_forward_request_duration_seconds_bucket` metric in explore?
Can you give more information on your setup?

**Comment by uhthomas** [comment]
I don't have that metric.

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/02c64c09-2e40-42b5-a1f5-e72f6887e896)

**Comment by dotdc** [comment]
Looks like this was removed in https://github.com/coredns/coredns/pull/6178
I'm probably going to remove this panel if it's fine for you @geekofalltrades (you contributed this in https://github.com/dotdc/grafana-dashboards-kubernetes/pull/34).

**Comment by dotdc** [comment]
Done in https://github.com/dotdc/grafana-dashboards-kubernetes/commit/23e46ede022b2b40bcd524dbb31145194aac5461
Thanks for reporting the issue @uhthomas !
