### ISSUE TITLE
deployment view

### ISSUE THREAD

**Issue by pid42** [dotdc/grafana-dashboards-kubernetes#32]
### Describe the enhancement you'd like

Currently there are views for:
- global
- namespace
- nodes
- pods

It would be nice to have a view that would show the status of the deployments (number or replicas, ...)

**Comment by dotdc** [comment]
Hi @pid42,

I don't think a deployment dashboard would be relevant, especially because it would mean make one for Statefulsets and Daemonsets too. 

You already have the number or replicas available and unavailable in the "namespace" view.
If this is not enough, can you please give more information on your use-case?

**Comment by dotdc** [comment]
Closing this issue

**Comment by Piroddi** [comment]
HI @dotdc, thanks for these charts, they amazing!

Would such a view not be beneficial to track the behaviour/performance of a specific application which spans multiple pods? Small use-case is to verify load is correctly being distributed across all pods in a deployments and not a single pod having massive spikes or consuming higher resources. 

I currently use the namespace view to achieve this, but since I have thousands of pods, the CPU & Memory usage by pod is just a massive colouring board :) I have to manually select all the pods linked to a deployment in both charts to investigate certain application pods

**Comment by dotdc** [comment]
@Piroddi @pid42 I'll see what I can do for this use-case. 
Re-opening

**Comment by dotdc** [comment]
I added a new `created_by` variable in `k8s-views-namespaces.json` to select a specific series of pods.
This will only affect the "Resources" and "Kubernetes Resources" rows.

The implemented solution should work evenly for Deployment, StatefulSet and Daemonset. 

@Piroddi @pid42 Let me know what you think and if you need anything else.

**Comment by dotdc** [comment]
Closing

**Comment by leoskyrocker** [comment]
Hi @dotdc, I'm just testing out how well this can be used to drill down on a particular type of application.
It turns out, because of our rapid development cycle, there are constantly new revision rolled out for a single deployment.

There are two problems we're facing:
1. the `created_by` filter has a lot of options because of the number of replicas and it's hard to view it for one deployment to view. We have to select all of the replicasets tied to the deployment.
2. the graphs are very difficult to read because they are currently summed by pod. (See screenshots)

Not sure how we should go about 1.

For 2, if we want to get a better sense of usage of one single deployment (doesn't matter how many pods), shouldn't it sum the timeseries up by (created_by) instead?

### CPU
<img width="543" alt="Screenshot 2023-09-22 at 6 42 54 PM" src="https://github.com/dotdc/grafana-dashboards-kubernetes/assets/2366893/3d8c2db7-5dc0-4b24-b144-2c6fa6bb029e">

### Memory
<img width="550" alt="Screenshot 2023-09-22 at 6 43 01 PM" src="https://github.com/dotdc/grafana-dashboards-kubernetes/assets/2366893/86a7eae7-4133-4161-94e3-187dd5d79ecb">
