### ISSUE TITLE
https://github.com/dotdc/grafana-dashboards-kubernetes/blob/master/dashboards/trivy

### ISSUE THREAD

**Issue by mohang6770** [dotdc/grafana-dashboards-kubernetes#40]
### Describe the bug

i am using the dashboard ( grafana-dashboards-kubernetes/dashboards/trivy ) but I am not getting any values for 'CVE vulnerabilities in All namespace(s)' and 'Other vulnerabilities in All namespace(s)', I have enabled OPERATOR_METRICS_VULN_ID_ENABLED= true in my trivy deployment and I am using the latest version of trivy operator and prometheus. could you please help

### How to reproduce?

1.install latest trivy-operator and try to use the grafana dashboard

### Expected behavior

show cve values

**Comment by dotdc** [comment]
This dashboards was made when I was using https://github.com/giantswarm/starboard-exporter.
I'm not sure trivy-operator is exposing any metrics like this, probably because of the cardinality issue.

Just in case, can you give the documentation link for `OPERATOR_METRICS_VULN_ID_ENABLED` ? 

Because it doesn't seems to be implemented in trivy-operator according to :
https://github.com/aquasecurity/trivy-operator/tree/main/deploy/helm#operator-configuration

**Comment by mohang6770** [comment]
@dotdc i have enabled it, still no luck..

**Comment by dotdc** [comment]
Ok found the flag, will make an update to make it work with trivy-operator.

**Comment by dotdc** [comment]
Just pushed an update, should work now.

[Updated k8s-addons-trivy-operator.json](https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-addons-trivy-operator.json)

Let me know!

**Comment by mohang6770** [comment]
Thanks Done it and its working..
