### ISSUE TITLE
[bug] broken panels on k8s-views-nodes in specific cases

### ISSUE THREAD

**Issue by dotdc** [dotdc/grafana-dashboards-kubernetes#44]
### Describe the bug

The `k8s-views-nodes.json` dashboard will have many broken panels in specific Kubernetes setups. 
This is currently the case on [OKE](https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/705).

Apparently, this happens when the `node` label from `kube_node_info` doesn't match the `nodename` label from `node_uname_info`.

Here's some extracted metrics from a broken setup where the labels differ. 

TL;DR: `node="k8s-wrk-002"` and `nodename="kind-kube-prometheus-stack-worker2"`.

kube_node_info: 
```
{
    __name__="kube_node_info",
    container="kube-state-metrics",
    container_runtime_version="containerd://1.6.19-46-g941215f49",
    endpoint="http", 
    instance="10.27.3.148:8080", 
    internal_ip="172.18.0.2", 
    job="kube-state-metrics", 
    kernel_version="6.2.12-arch1-1", 
    kubelet_version="v1.26.3", 
    kubeproxy_version="v1.26.3", 
    namespace="monitoring",
    node="k8s-wrk-002",
    os_image="Ubuntu 22.04.2 LTS",
    pod="kube-prometheus-stack-kube-state-metrics-6df68756d8-zvd58",
    pod_cidr="10.27.1.0/24",
    provider_id="kind://docker/kind-kube-prometheus-stack/kind-kube-prometheus-stack-worker2", 
    service="kube-prometheus-stack-kube-state-metrics", 
    system_uuid="8422f117-6154-45bd-97c0-e3dec80a3f60"
}
```

node_uname_info:
```
{
    __name__="node_uname_info", 
    container="node-exporter", 
    domainname="(none)", 
    endpoint="http-metrics", 
    instance="172.18.0.2:9100", 
    job="node-exporter", 
    machine="x86_64", 
    namespace="monitoring", 
    nodename="kind-kube-prometheus-stack-worker2", 
    pod="kube-prometheus-stack-prometheus-node-exporter-qvn22", 
    release="6.2.12-arch1-1", 
    service="kube-prometheus-stack-prometheus-node-exporter", 
    sysname="Linux", 
    version="#1 SMP PREEMPT_DYNAMIC Thu, 20 Apr 2023 16:11:55 +0000"
}
```

This issue will continue the discussion started in https://github.com/dotdc/grafana-dashboards-kubernetes/pull/41

@fcecagno @Chewie

### How to reproduce?

You can use https://github.com/dotdc/kind-lab, that will create a kind cluster with renamed nodes.

```bash
# Create the kind cluster
./start.sh

# Export configuration
export KUBECONFIG="$(pwd)/kind-kubeconfig.yml"

# Expose Grafana
kubectl port-forward svc/kube-prometheus-stack-grafana -n monitoring 3000:80
```

Open <http://localhost:3000>

login: admin
password: prom-operator

Open broken dashboard: 

<http://localhost:3000/d/k8s_views_nodes/kubernetes-views-nodes?orgId=1&refresh=30s>

### Expected behavior

Dashboard should work with a `relabel_configs` like suggested @Chewie.
The solution should be described in https://github.com/dotdc/grafana-dashboards-kubernetes#known-issues

**Comment by Chewie** [comment]
Thank you for the reproduction scenario!
I'll take a stab at documenting this and give some relabeling config.
My particular case was easier since there already was another label in grafana agent's node exporter that could be used for the nodename, but I'll need to investigate the scenario you provided to see if there's a way to make that info appear in node exporter.

**Comment by Chewie** [comment]
Update: turns out the solution was in plain sight, right in the [kube-prometheus-stack helm values](https://github.com/prometheus-community/helm-charts/blob/ac4e45620e60445ce4eae0aaf4fc367c540c105a/charts/kube-prometheus-stack/values.yaml#L1836).

This relabeling should take care of all situations where node-exporter is deployed through kube and decides to expose the name of its pod as a nodename.

I just need to check if this relabeling also works with the grafana agent (in theory it should, it uses the same codebase as prometheus for service discovery), then I'll open a PR documenting this relabeling :)

**Comment by Chewie** [comment]
That would be great! I drafted a PR with the workaround explanation, eager to know if this fix works for your setup!

**Comment by dotdc** [comment]
That's great!

@Chewie, does it work with the Grafana Agent?
@fcecagno, please let us know if the rule work on OKE.

**Comment by dotdc** [comment]
@fcecagno Workaround is available here : https://github.com/dotdc/grafana-dashboards-kubernetes#known-issues
