### ISSUE TITLE
The pod view should allow multi-selection (+`all`) for the `namespace` and `pod` variables [enhancement] 

### ISSUE THREAD

**Issue by aaaaahaaaaa** [dotdc/grafana-dashboards-kubernetes#93]
### Describe the enhancement you'd like

I find the lack of multiselect for the pod view very limiting. The view should allow to look at multiple workloads at once.

**Comment by dotdc** [comment]
Hi @aaaaahaaaaa ,

Do you think the `k8s-views-namespaces.json` dashboard with the `namespace` and `created_by` variables configured could work for what you need?

If not, could you please explain your use case?

I like the idea, but I need more context because some panels will have to be reworked, especially the ones in `Information`.

**Comment by aaaaahaaaaa** [comment]
Your pod dashboard shows more metrics, like resource usage and request/limit pressure. I like the metrics you display there but I would like to see and compare multiple pods on those graphs. I think the variables are only missing the `multi-select` + `all` options.

**Comment by dotdc** [comment]
Hi @aaaaahaaaaa,
Done in [v2.1.0](https://github.com/dotdc/grafana-dashboards-kubernetes/releases/tag/v2.1.0)
